# Generated by Django 5.2.5 on 2025-08-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_lecture_external_link_remove_lecture_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecture_type',
            field=models.CharField(choices=[('Live', 'Live'), ('Recorded', 'Recorded')], default='Recorded', help_text='Type of lecture: Live or Recorded', max_length=10),
        ),
        migrations.AddField(
            model_name='lecture',
            name='topic',
            field=models.CharField(blank=True, help_text='Topic of the lecture', max_length=200),
        ),
        migrations.AddField(
            model_name='lecture',
            name='upload_date',
            field=models.DateTimeField(blank=True, help_text='Lecture uploading date', null=True),
        ),
    ]
