# Generated by Django 5.2.6 on 2025-09-07 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=170)),
                ('thumbnail', models.URLField(blank=True, help_text='Course thumbnail image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(blank=True, help_text='Topic of the lecture', max_length=200)),
                ('lecture_type', models.CharField(choices=[('Live', 'Live'), ('Recorded', 'Recorded')], default='Recorded', help_text='Type of lecture: Live or Recorded', max_length=10)),
                ('upload_date', models.DateTimeField(blank=True, help_text='Lecture uploading date', null=True)),
                ('youtube_url', models.URLField(help_text='YouTube video URL')),
                ('questions', models.JSONField(default=list, help_text='List of external question links (LeetCode, GeeksforGeeks, etc.)')),
                ('code', models.TextField(blank=True, help_text='Python code snippet', null=True)),
                ('description', models.TextField(help_text='Lecture description')),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
            ],
        ),
    ]
