# Generated by Django 5.2.5 on 2025-08-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='external_link',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='video_link',
        ),
        migrations.AddField(
            model_name='lecture',
            name='code',
            field=models.TextField(blank=True, help_text='Python code snippet', null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='questions',
            field=models.JSONField(default=list, help_text='List of external question links (LeetCode, GeeksforGeeks, etc.)'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='youtube_url',
            field=models.URLField(default=1, help_text='YouTube video URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='Course thumbnail image URL'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='description',
            field=models.TextField(help_text='Lecture description'),
        ),
    ]
